// Exportación central de todos los componentes comunes
export { default as Alert } from './Alert/Alert';
export { default as Badge } from './Badge/Badge';
export { default as Button } from './Button/Button';
export { default as Card } from './Card/Card';
export { default as Input } from './Input/Input';
export { default as Modal } from './Modal/Modal';
export { default as Select } from './Select/Select';
export { default as Spinner } from './Spinner/Spinner';
export { default as Table } from './Table/Table';